apiVersion: apps/v1
kind: Deployment
metadata:
  name: shadowhunt-detector
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shadowhunt-detector
  template:
    metadata:
      labels:
        app: shadowhunt-detector
    spec:
      containers:
      - name: detector
        image: {{ .Values.images.detector }}
